name: RegularlyMessage
api: [4.0.0]
main: bbo51dog\regularlymessage\Main
version: 2.2.0
description: Send your messages regularly
author: bbo51dog
website: https://github.com/bbo51dog/RegularlyMessage